---
- name: Install RHEV
  hosts: rhv-host
  vars:
  pre_tasks:
    - name: Add vdsm user
      user:
        name: vdsm
        uid: 36
        group: 36
      
  roles:
    - { role: rhsm, tags: rhsm }
    - { role: nfs-server , tags: nfs }
  post_tasks:
    - name: Install hosted engine deploy packages
      yum:
        name:  "{{ item }}"
        state: installed
      with_items:
        - cockpit-ovirt-dashboard
        - ovirt-hosted-engine-setup

    - name: Enable and start services
      systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enable }}" 
      with_items:
        - { name: "cockpit.service", state: started, enable: yes }
        - { name: "cockpit.socket",  state: started, enable: yes }
        - { name: "firewalld",       state: stopped, enable: no  }
      tags:
        - services

    - name: Add NFS to iptables
      iptables:
        chain: INPUT
        state: "{{ item.state }}"
        protocol: "{{ item.proto }}"
        match: "{{ item.proto }}"
        destination_port: "{{ item.port }}"
        jump: ACCEPT
      with_items:
        - "{{ iptables_rules }}"
      tags: 
        - iptables
        - nfs
