---
- hosts: localhost
  connection: local
  gather_facts: no 
  vars_files:
    - ../ocp-vars.yml
  tasks:

    - name: Template Openshift hosts files
      template:
        src: hosts.j2
        dest: "{{ playbook_dir }}/inventory/hosts"
      run_once: true      

    - local_action: meta
        refresh_inventory

- name: call openshift pre-req play
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"

- name: call openshift deploy_cluster play
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml"
 

- hosts: localhost
  connection: local
  vars:
    admin_user: "{{ openshift_master_htpasswd_users.keys() }}"
    local_home: "{{ lookup('env','HOME') }}"
  tasks:
    - name: Install oc client
      yum:
        name: atomic-openshift-clients
        state: latest
      become: true
      notify: 
        - add cluster-admin

    - name: copy kube config
      fetch:
        src: ~/.kube/config
        dest: "{{ local_home }}/.kube/"
        flat: yes
      delegate_to: "{{ groups.masters[0] }}"
      notify: 
        - add cluster-admin

  handlers:
    - name: add cluster-admin
      shell: oc adm policy add-cluster-role-to-user cluster-admin "{{ admin_user }}"
