---
- name: Unregister VMs
  hosts: nodes:lb
  gather_facts: False
  tasks:
    - name: RHSM Unregister VMs
      redhat_subscription:
        state: absent
      register: task_result
      until: task_result is success
      retries: 10
      delay: 30
      ignore_errors: True

- name: oVirt infra destroy
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/vars.yml
    - ../ocp-vars.yml

  pre_tasks:
    - name: Log in to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"

  tasks:
    - name: Erase vms
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ item.name }}"
      with_items:
        - "{{ vms }}"

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"

    - name: remove ansible hosts file
      file:
        state: absent
        path: inventory/hosts
