- name: re-install everything
  hosts: localhost
  tasks:
    - debug:
        msg: "Erasing all VMs and re-installing openshift"

- import_playbook: remove-vms.yaml
  
- import_playbook: deploy-vms.yaml

- import_playbook: openshift-install.yaml
